# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBlu',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('corpus', models.CharField(max_length=1200)),
                ('price_flo', models.IntegerField(default=0)),
                ('price_com', models.IntegerField(default=0)),
                ('price_hon', models.IntegerField(default=0)),
                ('price_fav', models.IntegerField(default=0)),
                ('price_con', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reputation', models.IntegerField(default=-2)),
            ],
        ),
        migrations.CreateModel(
            name='MarketCon',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('corpus', models.CharField(max_length=1200)),
                ('price_flo', models.IntegerField(default=0)),
                ('price_com', models.IntegerField(default=0)),
                ('price_hon', models.IntegerField(default=0)),
                ('price_fav', models.IntegerField(default=0)),
                ('price_con', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketConOwner', to='battle.Character')),
            ],
        ),
        migrations.CreateModel(
            name='MarketOpp',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('corpus', models.CharField(max_length=1200)),
                ('price_flo', models.IntegerField(default=0)),
                ('price_com', models.IntegerField(default=0)),
                ('price_hon', models.IntegerField(default=0)),
                ('price_fav', models.IntegerField(default=0)),
                ('price_con', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketOppOwner', to='battle.Character')),
            ],
        ),
    ]
