# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcon',
            name='reputation',
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name='marketopp',
            name='reputation',
            field=models.IntegerField(default=-2),
        ),
    ]
