# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20160405_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcon',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='marketopp',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
