# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sestieri',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=255)),
                ('sestiere', models.CharField(max_length=255)),
                ('commentary', models.CharField(max_length=1200)),
                ('modified', models.DateTimeField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
