# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sestieri',
            name='commentary',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
