# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20160330_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponti',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=255)),
                ('pont', models.CharField(max_length=255)),
                ('commentary', models.CharField(max_length=1200, null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
