# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_pontijson_sestierijson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stradi',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=255)),
                ('via', models.CharField(max_length=255)),
                ('commentary', models.CharField(max_length=1200, null=True)),
                ('modified', models.DateTimeField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='PontiJson',
        ),
        migrations.DeleteModel(
            name='SestieriJson',
        ),
    ]
