# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('characterGid', models.AutoField(primary_key=True, serialize=False)),
                ('characterName', models.CharField(max_length=200)),
                ('characterClass', models.CharField(choices=[('Noble', 'Noble'), ('Merchant', 'Merchant'), ('Cleric', 'Cleric')], default='Cleric', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentGid', models.AutoField(primary_key=True, serialize=False)),
                ('equipmentType', models.CharField(choices=[('Arme', 'Arme'), ('Armure', 'Armure'), ('Spécial', 'Spécial')], default='Arme', max_length=200)),
                ('equipmentName', models.CharField(max_length=200)),
                ('equipmentSlot', models.CharField(choices=[('Main droite', 'Main droite'), ('Main gauche', 'Main gauche'), ('Armure', 'Armure')], default='Main droite', max_length=200)),
                ('modPAC', models.IntegerField(default=0)),
                ('modMOV', models.IntegerField(default=0)),
                ('modINI', models.IntegerField(default=0)),
                ('modSTR', models.IntegerField(default=0)),
                ('modEVA', models.IntegerField(default=0)),
                ('modDEF', models.IntegerField(default=0)),
                ('modFAV', models.IntegerField(default=0)),
                ('modMOR', models.IntegerField(default=0)),
                ('modSPE', models.CharField(default=0, max_length=200)),
                ('equipmentOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupGid', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=200)),
                ('groupMemberHealthy', models.IntegerField(default=30)),
                ('groupMemberInjured', models.IntegerField(default=0)),
                ('groupMemberDead', models.IntegerField(default=0)),
                ('groupPAC', models.IntegerField(default=6)),
                ('groupMOV', models.IntegerField(default=2)),
                ('groupINI', models.IntegerField(default=2)),
                ('groupSTR', models.IntegerField(default=2)),
                ('groupEVA', models.IntegerField(default=2)),
                ('groupDEF', models.IntegerField(default=2)),
                ('groupFAV', models.IntegerField(default=0)),
                ('groupMOR', models.IntegerField(default=0)),
                ('groupSPE', models.CharField(default=0, max_length=200)),
                ('equiArmor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiArmor', to='battle.Equipment')),
                ('equiLH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiLH', to='battle.Equipment')),
                ('equiRH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiRH', to='battle.Equipment')),
                ('groupOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerGid', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='characterOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Player'),
        ),
    ]
